- hosts: all
  pre_tasks:
    - name: Include vars file
      include_vars: vars.yml

    - set_fact:
        # No spaces to avoid breaking the url
        local_proxy_url: "{% if proxy_enabled %}http://{{ local_squid_host }}:{{ local_squid_port }}{% else %}{% endif %}"
  tasks:
    - name: Register proxy helpers
      import_role:
        name: proxy
      when: proxy_enabled

    - import_role:
        name: tools

    - name: Install terraform
      import_role:
        name: terraform
      when: terraform_enabled

    - name: Install Virtualbox
      notify: Reconfigure virtualbox packages
      become: yes
      apt:
        name: ["virtualbox", "virtualbox-dkms", "linux-headers-generic"]
        state: present

  handlers:
    - name: Reconfigure virtualbox packages
      # https://askubuntu.com/a/465455
      shell: |
        dpkg-reconfigure -fnoninteractive virtualbox-dkms virtualbox
        modprobe vboxdrv
      become: yes

    - name: Install fzf
      shell: ~/.fzf/install --all
