- name: Check if proxy cert exists
  notify: Fetch certs
  stat:
    path: "{{ certs_path }}/ansible-custom-cert.crt"
  register: cert_exists
  changed_when: not cert_exists.stat.exists

- name: Install squid as local reverse proxy
  become: yes
  apt:
    name: squid
    state: present

# Handled as task to update existing squid configurations on file changes
- name: Copy squid config
  notify: Restart squid
  become: yes
  template:
    src: squid-config.j2
    dest: /etc/squid/squid.conf

- name: Set squid proxy by environment vars
  become: yes
  blockinfile:
    path: /etc/environment
    block: |
      export http_proxy={{ local_proxy_url }}
      export no_proxy={{ no_proxy }}
      export https_proxy={{ local_proxy_url }}
      export HTTP_PROXY={{ local_proxy_url }}
      export HTTPS_PROXY={{ local_proxy_url }}
      export NO_PROXY={{ no_proxy }}

# Firefox cert store to trust the proxy certificate since the browser has its own cert store
- name: Check if firefox is installed
  shell: which firefox
  register: ff_check_result
  changed_when: False

- name: Install dependencies for firefox certutil
  become: yes
  when: ff_check_result.rc == 0
  apt: 
    name: "libnss3-tools"
    state: present

- name: Register certs in firefox cert store if not present
  shell: "{{ lookup('template', 'register-firefox-certs.j2') }}"
  register: ff_register_result
  changed_when: ff_register_result.stdout.find("Register") != -1
  when: ff_check_result.rc == 0